#pragma once

namespace Neon
{
	namespace Graphics
	{
		enum FramebufferAttachmentFormat
		{
			NEON_FRAMEBUFFER_ATTACHMENT_FORMAT_NONE = 0x00,

			// DepthStencilFormats
			NEON_FRAMEBUFFER_ATTACHMENT_FORMAT_D32_FLOAT,
			NEON_FRAMEBUFFER_ATTACHMENT_FORMAT_D32_FLOAT_S8_UINT,
			NEON_FRAMEBUFFER_ATTACHMENT_FORMAT_D24_UNORM_S8_UINT,
			NEON_FRAMEBUFFER_ATTACHMENT_FORMAT_D16_UNORM,
		};
	}
}